$A=\begin{pmatrix}0&1&-1\\-1&0&1\\1&-1&0\end{pmatrix}$

A这个矩阵展示了当玩家以行row进行游戏，而对手以列进行游戏的情况下，A的payoff matrix

In [6]:
import nashpy as nash
import numpy as np

A = np.array([[0, 1, -1], [-1, 0, 1], [1, -1, 0]])
rps = nash.Game(A)
rps

Zero sum game with payoff matrices:

Row player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

Column player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

在数学表达里，我们可以用$\sigma$来表达玩家的策略

例如$\sigma_r=(0,0,1)$代表行玩家总是使用第三个动作

$\sigma_c=(1,0,0)$代表列玩家总是使用第一个动作

当我们知道具体策略时，可以通过以下方法来获取某个玩家的Utility
$\sigma_rA\sigma_c^T$

In [7]:
# 石头 剪刀 布
# 行玩家永远出布
sigma_r = [0, 0, 1]
# 列玩家永远出剪刀
sigma_c = [0, 1, 0]
# 将策略分别配置到游戏中
rps[sigma_r, sigma_c]

# 行玩家的Utility为-1（一直输）
# 列玩家的Utility为1（一直赢）

array([-1,  1])

In [8]:
# 如果这时候行玩家还是出布
# 但是列玩家混合石头和剪刀

sigma_c = [1 / 2, 1 / 2, 0]
rps[sigma_r, sigma_c]

array([0., 0.])

In [9]:
sigma_r = [0, 1 / 2, 1 / 2]
rps[sigma_r, sigma_c]

array([-0.25,  0.25])

我们也可以通过nashpy库来求解纳什均衡问题。

In [10]:
eqs = rps.support_enumeration()
list(eqs)

[(array([0.33333333, 0.33333333, 0.33333333]),
  array([0.33333333, 0.33333333, 0.33333333]))]